name: event_ticketing
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter:
  http: ^1.3.0
  intl: ^0.20.2
  provider: ^6.1.2
  qr_code_scanner_plus: ^2.0.10+1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true
